default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  database: <%= ENV.fetch("DATABASE_NAME") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  pool: <%= ENV.fetch("DATABASE_POOL") %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>

